"Resource/UI/MainBuyMenu.res"
{
	"BuySubMenu_CT"
	{
		"ControlName"		"CCSBuyMenu_CT"
		"fieldName"		"BuySubMenu_CT"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"640"
		"tall"			"480"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"setTitleBarVisible"	"0"
	}
	"ItemInfo"
	{
		"ControlName"		"Panel"
		"fieldName"		"ItemInfo"
		"xpos"		"1680"
		"ypos"		"1160"
		"wide"		"400"
		"tall"		"380"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"Title"
	{
		"ControlName"		"Label"
		"fieldName"		"Title"
				"xpos"		"75"
		"ypos"		"22"
		"wide"		"500"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_Buy_MenuCAPS"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"MenuTitle"
		"wrap"		"0"
	}
	"money"
	{
		"ControlName"		"Label"
		"fieldName"		"money"
		"xpos"		"200"
		"ypos"		"36"
		"wide"		"160"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#Cstrike_Select_Category"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"	"1"
	}
	"selectCategory"
	{
		"ControlName"		"Label"
		"fieldName"		"selectCategory"
				"xpos"		"52"
		"ypos"		"80"
		"wide"		"170"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_Select_Category"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"	"1"
	}
	"quickBuy"
	{
		"ControlName"		"Label"
		"fieldName"		"quickBuy"
		"xpos"		"248"
		"ypos"		"238"
		"wide"		"170"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_Quick_Buy"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"	"1"
	}
	"favorites"
	{
		"ControlName"		"Label"
		"fieldName"		"favorites"
		"xpos"		"428"
		"ypos"		"238"
		"wide"		"170"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_TER_Favorites"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"	"1"
	}
	"pistols"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"pistols"
				"xpos"		"52"
		"ypos"		"116"
		"wide"		"170"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_Pistols"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"UI/BuyPistols_CT.res"
		"Default"		"0"
	}
	"shotguns"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"shotguns"
				"xpos"		"52"
		"ypos"		"148"
		"wide"		"170"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_Shotguns"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"UI/BuyShotguns.res"
		"Default"		"0"
	}
	"submachineguns"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"submachineguns"
				"xpos"		"52"
		"ypos"		"180"
		"wide"		"170"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_SubMachineGuns"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"UI/BuySubMachineGuns_CT.res"
		"Default"		"0"
	}
	"rifles"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"rifles"
				"xpos"		"52"
		"ypos"		"212"
		"wide"		"170"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_Rifles"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"UI/BuyRifles_CT.res"
		"Default"		"0"
	}
	"machineguns"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"machineguns"
				"xpos"		"52"
		"ypos"		"244"
		"wide"		"170"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_MachineGuns"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"UI/BuyMachineGuns.res"
		"Default"		"0"
	}
	"primaryammo"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"primaryammo"
				"xpos"		"52"
		"ypos"		"276"
		"wide"		"170"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_Prim_Ammo"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"primammo"
		"Default"		"0"
	}
	"secammo"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"secammo"
				"xpos"		"52"
		"ypos"		"308"
		"wide"		"170"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_Sec_Ammo"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"secammo"
		"Default"		"0"
	}
	"equipment"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"equipment"
		"xpos"		"52"
		"ypos"		"340"
		"wide"		"170"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_Equipment"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"UI/BuyEquipment_CT.res"
		"Default"		"0"
	}

	"CancelButton"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"CancelButton"
				"xpos"		"52"
		"ypos"		"390"
		"wide"		"170"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_Cancel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"vguicancel"
		"Default"		"1"
	}
	"AutobuyButton"
	{
		"ControlName"		"Button"
		"fieldName"		"AutobuyButton"
		"xpos"		"248"
		"ypos"		"264"
		"wide"		"170"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_BuyMenuAutobuy"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"autobuy"
		"Default"		"0"
	}
	"RebuyButton"
	{
		"ControlName"		"Button"
		"fieldName"		"RebuyButton"
		"xpos"		"248"
		"ypos"		"296"
		"wide"		"170"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_BuyMenuRebuy"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"rebuy"
		"Default"		"0"
	}
	"BuyPresetButtonA"
	{
		"ControlName"		"Button"
		"fieldName"		"BuyPresetButtonA"
		"xpos"		"428"
		"ypos"		"264"
		"wide"		"118"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_BuyMenuPreset1"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"cl_buy_favorite 1"
		"Default"		"0"
	}
	"BuyPresetButtonSetA"
	{
		"ControlName"		"Button"
		"fieldName"		"BuyPresetButtonSetA"
		"xpos"		"550"
		"ypos"		"264"
		"wide"		"38"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_SetPreset"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"cl_buy_favorite_query_set 1"
		"Default"		"0"
	}
	"BuyPresetButtonB"
	{
		"ControlName"		"Button"
		"fieldName"		"BuyPresetButtonB"
		"xpos"		"428"
		"ypos"		"296"
		"wide"		"118"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_BuyMenuPreset2"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"cl_buy_favorite 2"
		"Default"		"0"
	}
	"BuyPresetButtonSetB"
	{
		"ControlName"		"Button"
		"fieldName"		"BuyPresetButtonSetB"
		"xpos"		"550"
		"ypos"		"296"
		"wide"		"38"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_SetPreset"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"cl_buy_favorite_query_set 2"
		"Default"		"0"
	}
	"BuyPresetButtonC"
	{
		"ControlName"		"Button"
		"fieldName"		"BuyPresetButtonC"
		"xpos"		"428"
		"ypos"		"328"
		"wide"		"118"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_BuyMenuPreset3"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"cl_buy_favorite 3"
		"Default"		"0"
	}
	"BuyPresetButtonSetC"
	{
		"ControlName"		"Button"
		"fieldName"		"BuyPresetButtonSetC"
		"xpos"		"550"
		"ypos"		"328"
		"wide"		"38"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_SetPreset"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"cl_buy_favorite_query_set 3"
		"Default"		"0"
	}
	"BuyPresetButtonD"
	{
		"ControlName"		"Button"
		"fieldName"		"BuyPresetButtonD"
		"xpos"		"428"
		"ypos"		"360"
		"wide"		"118"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_BuyMenuPreset4"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"cl_buy_favorite 4"
		"Default"		"0"
	}
	"BuyPresetButtonSetD"
	{
		"ControlName"		"Button"
		"fieldName"		"BuyPresetButtonSetD"
		"xpos"		"550"
		"ypos"		"360"
		"wide"		"38"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_SetPreset"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"cl_buy_favorite_query_set 4"
		"Default"		"0"
	}
	"BuyPresetButtonE"
	{
		"ControlName"		"Button"
		"fieldName"		"BuyPresetButtonE"
		"xpos"		"428"
		"ypos"		"392"
		"wide"		"118"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_BuyMenuPreset5"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"cl_buy_favorite 5"
		"Default"		"0"
	}
	"BuyPresetButtonSetE"
	{
		"ControlName"		"Button"
		"fieldName"		"BuyPresetButtonSetE"
		"xpos"		"550"
		"ypos"		"392"
		"wide"		"38"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_SetPreset"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"cl_buy_favorite_query_set 5"
		"Default"		"0"
	}
	"BuyPresetEditButton"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"BuyPresetEditButton"
		"xpos"		"460"
		"ypos"		"340"
		"wide"		"120"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_BuyPresetEditPresetsButton"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"buy_preset_edit reopen"
		"Default"		"0"
	}

	"loadoutLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"loadoutLabel"
		"xpos"		"272"
		"ypos"		"80"
		"wide"		"284"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_Current_Loadout"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"	"1"
	}
	"loadoutPanel"
	{
		"ControlName"		"Panel"
		"fieldName"		"loadoutPanel"
		"xpos"		"272"
		"ypos"		"102"
		"wide"		"284"
		"tall"		"112"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
	}
}
