"Resource/UI/BuyRifles_CT.res"
{
	"BuySubMenu"
	{
		"ControlName"		"WizardSubPanel"
		"fieldName"		"BuySubMenu"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"640"
		"tall"			"480"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}

	"Title"
	{
		"ControlName"		"Label"
		"fieldName"		"Title"
				"xpos"		"75"
		"ypos"		"22"
		"wide"		"500"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_RiflesLabel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"MenuTitle"
		"wrap"		"0"
	}

	"ItemInfo"
	{
		"ControlName"		"Panel"
		"fieldName"		"ItemInfo"
		"xpos"		"244"
		"ypos"		"116"
		"wide"		"400"
		"tall"		"380"
		"autoResize"		"3"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}

	"famas"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"famas"
		"xpos"			"52"
		"ypos"			"116"
		"wide"			"170"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#Cstrike_Famas"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"command"		"famas"
		"cost"			"2250"
	}

	"scout"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"scout"
		"xpos"			"52"
		"ypos"			"148"
		"wide"			"170"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#Cstrike_Scout_CT"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"scout"
		"cost"			"2750"
		"as_restrict"		"1"
	}

	"m4a1"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"m4a1"
		"xpos"			"52"
		"ypos"			"180"
		"wide"			"170"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#Cstrike_M4A1"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"m4a1"
		"cost"			"3100"
	}
	
	"aug"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"aug"
		"xpos"			"52"
		"ypos"			"212"
		"wide"			"170"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_Aug"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"aug"
		"cost"			"3500"
	}
	
	"sg550"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"sg550"
		"xpos"			"52"
		"ypos"			"244"
		"wide"			"170"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_SG550"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"sg550"
		"cost"			"4200"
	}
		
	"awp"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"awp"
		"xpos"			"52"
		"ypos"			"276"
		"wide"			"170"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_AWP_CT"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"awp"
		"cost"			"4750"
		"as_restrict"		"1"
	}
		

	"CancelButton"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"CancelButton"
		"xpos"			"52"
		"ypos"			"380"
		"wide"			"170"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_Cancel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"vguicancel"
		"Default"		"1"
	}
}
