"Resource/UI/Loadout.res"
{
	"mainBackground"
	{
		"ControlName"		"Divider"
		"fieldName"		"mainBackground"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"284"
		"tall"		"112"
		"autoResize"		"3"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"vpos"		"-1"
		"lines"
		{
			"1"		"0 54 283 54"
			"2"		"160 0 160 54"
			"3"		"124 54 124 112"
		}
	}

	"primary"
	{
		"ControlName"		"Panel"
		"fieldName"		"primary"
		"xpos"		"4"
		"ypos"		"4"
		"wide"		"158"
		"tall"		"46"
		"visible"		"1"
		"enabled"		"1"
		"zpos"		"3"
	}
	"secondary"
	{
		"ControlName"		"Panel"
		"fieldName"		"secondary"
		"xpos"		"158"
		"ypos"		"4"
		"wide"		"128"
		"tall"		"46"
		"visible"		"1"
		"enabled"		"1"
		"zpos"		"3"
	}
	"hegrenade"
	{
		"ControlName"		"Panel"
		"fieldName"		"hegrenade"
		"xpos"		"-8"
		"ypos"		"65"
		"wide"		"60"
		"tall"		"35"
		"visible"		"1"
		"enabled"		"1"
		"zpos"		"3"
	}
	"smokegrenade"
	{
		"ControlName"		"Panel"
		"fieldName"		"smokegrenade"
		"xpos"		"32"
		"ypos"		"65"
		"wide"		"60"
		"tall"		"35"
		"visible"		"1"
		"enabled"		"1"
		"zpos"		"3"
	}
	"flashbang"
	{
		"ControlName"		"Panel"
		"fieldName"		"flashbang"
		"xpos"		"72"
		"ypos"		"65"
		"wide"		"60"
		"tall"		"35"
		"visible"		"1"
		"enabled"		"1"
		"zpos"		"3"
	}
	"defuser"
	{
		"ControlName"		"Panel"
		"fieldName"		"defuser"
		"xpos"		"128"
		"ypos"		"55"
		"wide"		"44"
		"tall"		"56"
		"visible"		"1"
		"enabled"		"1"
		"zpos"		"3"
	}
	"nightvision"
	{
		"ControlName"		"Panel"
		"fieldName"		"nightvision"
		"xpos"		"175"
		"ypos"		"55"
		"wide"		"44"
		"tall"		"56"
		"visible"		"1"
		"enabled"		"1"
		"zpos"		"3"
	}
	"armor"
	{
		"ControlName"		"Panel"
		"fieldName"		"armor"
		"xpos"		"220"
		"ypos"		"55"
		"wide"		"60"
		"tall"		"56"
		"visible"		"1"
		"enabled"		"1"
		"zpos"		"3"
	}
}