"resource/OptionsSubVideoAdvancedDlg.res"
{
	"OptionsSubVideoAdvancedDlg"
	{
		"ControlName"		"COptionsSubVideoAdvancedDlg"
		"fieldName"		"OptionsSubVideoAdvancedDlg"
		"xpos"		"c-171"
		"ypos"		"c-85"
		"wide"		"352"
		"tall"		"161"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"1"
		"title"		"#GameUI_VideoAdvanced_Title"
	}

	"AnisotropicFiltering"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"AnisotropicFiltering"
		"xpos"		"22"
		"ypos"		"60"
		"wide"		"132"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"8"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}

	"DetailTexture"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"DetailTexture"
		"xpos"		"186"
		"ypos"		"38"
		"wide"		"132"
		"tall"		"28"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"13"
		"labelText"		"#GameUI_DetailTextures"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
		"selected"		"0"
	}

	"WaterReflect"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"WaterReflect"
		"xpos"		"186"
		"ypos"		"60"
		"wide"		"132"
		"tall"		"28"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"13"
		"labelText"		"#GameUI_WaterReflect"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
		"selected"		"0"
	}

	"WaitForVSync"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"WaitForVSync"
		"xpos"		"186"
		"ypos"		"82"
		"wide"		"152"
		"tall"		"28"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"13"
		"labelText"		"#GameUI_VSync"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
		"selected"		"0"
	}

	"Label1"
	{
		"ControlName"		"Label"
		"fieldName"		"Label1"
		"xpos"		"22"
		"ypos"		"34"
		"wide"		"132"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_AnisotropicFiltering"
		"textAlignment"		"west"
		"associate"		"AnisotropicFiltering"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}

	"Button1"
	{
		"ControlName"		"Button"
		"fieldName"		"Button1"
		"xpos"		"160"
		"ypos"		"119"
		"wide"		"80"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"16"
		"labelText"		"#GameUI_OK"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"OK"
		"Default"		"1"
		"selected"		"0"
	}
	"Button2"
	{
		"ControlName"		"Button"
		"fieldName"		"Button2"
		"xpos"		"252"
		"ypos"		"119"
		"wide"		"80"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"17"
		"labelText"		"#GameUI_Cancel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"Close"
		"Default"		"0"
		"selected"		"0"
	}
}
