"Resource\OptionsSubAudio.res"
{
	"EAX"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"EAX"
		"xpos"		"249"
		"ypos"		"95"
		"wide"		"212"
		"tall"		"28"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"5"
		"labelText"		"#GameUI_EnableEAX"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"A3D"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"A3D"
		"xpos"		"249"
		"ypos"		"125"
		"wide"		"214"
		"tall"		"28"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"6"
		"labelText"		"#GameUI_EnableA3D"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"SFXSlider"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"SFXSlider"
		"xpos"		"40"
		"ypos"		"57"
		"wide"		"160"
		"tall"		"36"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"leftText"		""
		"rightText"		""
	}
	"MusicSlider"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"MusicSlider"
		"xpos"		"40"
		"ypos"		"118"
		"wide"		"160"
		"tall"		"36"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"leftText"		""
		"rightText"		""
	}
	"SoundQuality"
	{
		"ControlName"		"CLabeledCommandComboBox"
		"fieldName"		"SoundQuality"
		"xpos"		"256"
		"ypos"		"64"
		"wide"		"180"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"4"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
	}
	"sfx label"
	{
		"ControlName"		"Label"
		"fieldName"		"sfx label"
		"xpos"		"42"
		"ypos"		"34"
		"wide"		"160"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_SoundEffectVolume"
		"textAlignment"		"west"
		"associate"		"SFX Slider"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	"mp3 label"
	{
		"ControlName"		"Label"
		"fieldName"		"mp3 label"
		"xpos"		"40"
		"ypos"		"96"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_MP3Volume"
		"textAlignment"		"west"
		"associate"		"MP3 Volume"
		"dulltext"		"0"
		"brighttext"		"0"
	}

	"Label1"
	{
		"ControlName"		"Label"
		"fieldName"		"Label1"
		"xpos"		"256"
		"ypos"		"40"
		"wide"		"179"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_SoundQuality"
		"textAlignment"		"west"
		"associate"		"Sound Quality"
		"dulltext"		"0"
		"brighttext"		"0"
	}
}
