"Resource/UI/BackgroundPanel.res"
{
	"ViewPortBackGround"
	{
		"ControlName"		"Frame"
		"fieldName"		"ViewPortBackGround"
		"xpos"		"c-320"
		"ypos"		"0"
		"wide"		"640"
		"tall"		"480"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"0"
	}
	"TopLeftPanel"
	{
		"ControlName"		"BitmapImagePanel"
		"fieldName"		"TopLeftPanel"
		"xpos"		"20"
		"ypos"		"20"
		"wide"		"10"
		"tall"		"10"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"image"			""
	}
	"TopRightPanel"
	{
		"ControlName"		"BitmapImagePanel"
		"fieldName"		"TopRightPanel"
		"xpos"		"610"
		"ypos"		"20"
		"wide"		"10"
		"tall"		"10"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"image"			"gfx/vgui/round_corner_ne"
	}
	"BottomLeftPanel"
	{
		"ControlName"		"BitmapImagePanel"
		"fieldName"		"BottomLeftPanel"
		"xpos"		"20"
		"ypos"		"450"
		"wide"		"10"
		"tall"		"10"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"image"			"gfx/vgui/round_corner_sw"
	}
	"BottomRightPanel"
	{
		"ControlName"		"BitmapImagePanel"
		"fieldName"		"BottomRightPanel"
		"xpos"		"610"
		"ypos"		"450"
		"wide"		"10"
		"tall"		"10"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"image"			"gfx/vgui/round_corner_se"
	}
	"GapPanel"
	{
		"ControlName"		"Panel"
		"fieldName"		"GapPanel"
		"xpos"		"20"
		"ypos"		"72"
		"wide"		"600"
		"tall"		"2"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"ExclamationPanel"
	{
		"ControlName"		"BitmapImagePanel"
		"fieldName"		"ExclamationPanel"
		"xpos"		"26"
		"ypos"		"26"
		"wide"		"40"
		"tall"		"40"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"image"			"gfx/vgui/CS_logo"
		"imagecolor"		"FgColor"
	}
	"CaptionLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"CaptionLabel"
		"xpos"		"70"
		"ypos"		"22"
		"wide"		"450"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"Title"
	}
}
 