"Resource/UI/BottomSpectator.res"
{
	"specmenu"
	{
		"ControlName"		"Frame"
		"fieldName"		"specmenu"
		"xpos"			"0"
		"ypos"			"431"
		"wide"			"640"
		"tall"			"55"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
	}
	"settingscombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"settingscombo"
		"xpos"			"13"
		"ypos"			"14"
		"wide"			"126"
		"tall"			"22"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"	"0"
		"textAlignment"		"west"
	}
	"playercombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"playercombo"
		"xpos"			"c-141"
		"ypos"			"14"
		"wide"			"282"
		"tall"			"22"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"	"0"
		"textAlignment"		"center"
	}
	"viewcombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"viewcombo"
		"xpos"			"r139"
		"ypos"			"14"
		"wide"			"126"
		"tall"			"22"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"	"0"
		"textAlignment"		"west"
	}
	"specprev"
	{
		"ControlName"		"Button"
		"fieldName"		"specprev"
		"xpos"			"c-166"
		"ypos"			"14"
		"wide"			"20"
		"tall"			"22"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"textHidden"		"0"
		"command"		"specprev"
		"textAlignment"		"center"
	}
	"specnext"
	{
		"ControlName"		"Button"
		"fieldName"		"specnext"
		"xpos"			"c146"
		"ypos"			"14"
		"wide"			"20"
		"tall"			"22"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"textHidden"		"0"
		"command"		"specnext"
		"textAlignment"		"center"
	}

}
