"Resource/UI/BuyPresetButton.res"
{
	"ImagePanel"
	{
		"ControlName"		"EditablePanel"
		"fieldName" 		"ImagePanel"
		"visible" 		"1"
		"enabled" 		"1"
		"xpos"			"0"
		"ypos"			"0"
		"wide"	 		"118"
		"tall"	 		"20"
	}

	"primary"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"primary"
		"xpos"		"-5"
		"ypos"		"1"
		"wide"		"100"
		"tall"		"18"
		"visible"		"1"
		"enabled"		"1"
		"zpos"		"3"
		"image"		""
		"scaleImage"	"1"
		"centerImage"	"1"
	}
	"secondary"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"secondary"
		"xpos"		"70"
		"ypos"		"3"
		"wide"		"50"
		"tall"		"14"
		"visible"		"1"
		"enabled"		"1"
		"zpos"		"3"
		"image"		""
		"scaleImage"	"1"
		"centerImage"	"1"
	}
	"knife"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"knife"
		"xpos"		"478"
		"ypos"		"4"
		"wide"		"84"
		"tall"		"50"
		"visible"		"0"
		"enabled"		"1"
		"zpos"		"3"
		"image"		""
		"scaleImage"	"1"
		"centerImage"	"1"
	}
}