"Resource/UI/BuyRifles_TER.res"
{
	"BuySubMenu"
	{
		"ControlName"		"WizardSubPanel"
		"fieldName"		"BuySubMenu"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"640"
		"tall"			"480"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}

	"Title"
	{
		"ControlName"		"Label"
		"fieldName"		"Title"
		"xpos"		"75"
		"ypos"		"22"
		"wide"		"500"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_RiflesLabel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"MenuTitle"
		"wrap"		"0"
	}

	"ItemInfo"
	{
		"ControlName"		"Panel"
		"fieldName"		"ItemInfo"
		"xpos"		"244"
		"ypos"		"116"
		"wide"		"400"
		"tall"		"380"
		"autoResize"		"3"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}

	"galil"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"galil"
		"xpos"			"52"
		"ypos"			"116"
		"wide"			"170"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#Cstrike_Galil"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"command"		"galil"
		"cost"			"2000"
	}

	"ak47"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"ak47"
		"xpos"			"52"
		"ypos"			"148"
		"wide"			"170"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#Cstrike_AK47"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"command"		"ak47"
		"cost"			"2500"
	}

	"scout"
	{
		"ControlName"	"MouseOverPanelButton"
		"fieldName"		"scout"
		"xpos"			"52"
		"ypos"			"180"
		"wide"			"170"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#Cstrike_Scout_TER"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"command"		"scout"
		"cost"			"2750"
		"as_restrict"		"1"
	}
	
	"sg552"
	{
		"ControlName"	"MouseOverPanelButton"
		"fieldName"		"sg552"
		"xpos"			"52"
		"ypos"			"212"
		"wide"			"170"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#Cstrike_SG552"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"command"		"sg552"
		"cost"			"3500"
		"as_restrict"		"1"
	}

	"awp"
	{
		"ControlName"	"MouseOverPanelButton"
		"fieldName"		"awp"
		"xpos"			"52"
		"ypos"			"244"
		"wide"			"170"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#Cstrike_AWP_TER"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"command"		"awp"
		"cost"			"4750"
	}

	"g3sg1"
	{
		"ControlName"	"MouseOverPanelButton"
		"fieldName"		"g3sg1"
		"xpos"			"52"
		"ypos"			"276"
		"wide"			"170"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#Cstrike_G3SG1"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"command"		"g3sg1"
		"cost"			"5000"
		"as_restrict"		"1"
	}

	"CancelButton"
	{
		"ControlName"	"MouseOverPanelButton"
		"fieldName"		"CancelButton"
		"xpos"			"52"
		"ypos"			"380"
		"wide"			"170"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#Cstrike_Cancel"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"Command"		"vguicancel"
		"Default"		"1"
	}
}
