"Resource/UI/ScoreBoard.res"
{
	"scores"
	{
		"ControlName"			"CCSClientScoreBoardDialog"
		"fieldName"				"scores"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"90"
		"wide"					"f0"
		"tall"					"480"
		"settitlebarvisible"	"0"
		"paintbackground"	"0"
	}
	
	"ScoreboardBackground"
	{
		"ControlName"	        "ScalableImagePanel"
		"fieldName"		        "ScoreboardBackground"
		"xpos"		            "c-300"
		"ypos"		            "c-186"
		"wide"		            "600"
		"tall"		            "372"
		"visible"				"1"
		"enabled"				"1"
		"image"					"scoreboard/panel-scoreboard"
		"scaleImage"			"1"
		"drawcolor"			"255 255 255 220"
	}

	"MapName"
	{
		"ControlName"			"Label"
		"fieldName"				"MapName"
		"xpos"					"c-290"
		"ypos"					"c-179"
		"zpos"					"4"
		"wide"					"60"
		"tall"					"15"
		"visible"				"0"
		"enabled"				"1"
		"labelText"				"%mapname%"
		"textAlignment"			"west"
		"dulltext"				"0"
		"brighttext"			"1"
		"font"					"ScoreboardHeader"
		"fgcolor_override"		"255 177 0 255"
	}

	"ServerNameLabel"
	{
		"ControlName"			"Label"
		"fieldName"				"ServerNameLabel"
		"xpos"					"c-292"
		"ypos"					"c-179"
		"zpos"					"4"
		"wide"					"445"
		"tall"					"15"
		"visible"				"1"
		"enabled"				"1"
		"labelText"				""
		"textAlignment"			"west"
		"dulltext"				"0"
		"brighttext"			"1"
		"font"					"ScoreboardHeader"
		"fgcolor_override"		"255 177 0 255"
	}

	"Icon_Clock"
	{
		"ControlName"	"ImagePanel"
		"fieldName"			"Icon_Clock"
		"xpos"				"c+275"
		"ypos"				"c-181"
		"zpos"				"4"
		"wide"			"16"
		"tall"			"16"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"image"			"gfx/vgui/timer"
		"scaleImage"	"1"
		"fgcolor_override"	"255 177 0 255"
	}

	"Label_Clock"
	{
		"ControlName"			"Label"
		"fieldName"				"Label_Clock"
		"xpos"					"c+205"
		"ypos"					"c-179"
		"zpos"					"4"
		"wide"					"70"
		"tall"					"20"
		"visible"				"1"
		"enabled"				"1"
		"labelText"				""
		"textAlignment"			"east"
		"dulltext"				"0"
		"brighttext"			"1"
		"font"					"ScoreboardHeader"
		"fgcolor_override"		"255 177 0 255"
	}

	"CT_Label"
	{
		"ControlName"		"Label"
		"fieldName"			"CT_Label"
		"xpos"				"c-288"
		"ypos"				"c-158"
		"zpos"				"4"
		"wide"				"200"
		"tall"				"15"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			""
		"textAlignment"		"south-west"
		"font"				"ScoreboardTeamName"
		"fgcolor_override"	"216 220 223 255"
	}

	"CTPlayersAlive"
	{
		"ControlName"		"Label"
		"fieldName"			"CTPlayersAlive"
		"xpos"				"c-288"
		"ypos"				"c-140"
		"zpos"				"4"
		"wide"				"160"
		"tall"				"12"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			""
		"textAlignment"		"west"
		"font"				"ScoreboardPlayersAlive"
		"fgcolor_override"	"216 220 223 255"
	}

	"CTTeamScore"
	{
		"ControlName"		"Label"
		"fieldName"			"CTTeamScore"
		"xpos"				"c-107"
		"ypos"				"c-162"
		"zpos"				"4"
		"wide"				"100"
		"tall"				"40"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			""
		"textAlignment"		"east"
		"font"				"ScoreboardScore"
		"fgcolor_override"	"216 220 223 255"
	}

	"T_Label"
	{
		"ControlName"		"Label"
		"fieldName"			"T_Label"
		"xpos"				"c+88"
		"ypos"				"c-158"
		"zpos"				"4"
		"wide"				"200"
		"tall"				"15"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			""
		"textAlignment"		"south-east"
		"font"				"ScoreboardTeamName"
		"fgcolor_override"	"216 220 223 255"
	}

	"TPlayersAlive"
	{
		"ControlName"		"Label"
		"fieldName"			"TPlayersAlive"
		"xpos"				"c+128"
		"ypos"				"c-140"
		"zpos"				"4"
		"wide"				"160"
		"tall"				"12"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			""
		"textAlignment"		"east"
		"font"				"ScoreboardPlayersAlive"
		"fgcolor_override"	"216 220 223 255"
	}

	"TTeamScore"
	{
		"ControlName"		"Label"
		"fieldName"			"TTeamScore"
		"xpos"				"c+7"
		"ypos"				"c-162"
		"zpos"				"4"
		"wide"				"100"
		"tall"				"40"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			""
		"textAlignment"		"west"
		"font"				"ScoreboardScore"
		"fgcolor_override"	"216 220 223 255"
	}

	"CTPlayerLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"CTPlayerLabel"
		"xpos"				"c-284"
		"ypos"				"c-125"
		"zpos"				"4"
		"wide"				"60"
		"tall"				"15"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"#Cstrike_SB_PlayerName"
		"textAlignment"		"west"
		"font"				"ScoreboardColumns"
		"fgcolor_override"	"150 200 255 255"
	}

	"CTPlayerScoreLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"CTPlayerScoreLabel"
		"xpos"				"c-105"
		"ypos"				"c-125"
		"zpos"				"4"
		"wide"				"30"
		"tall"				"15"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"#Cstrike_SB_Score"
		"textAlignment"		"center"
		"font"				"ScoreboardColumns"
		"fgcolor_override"	"150 200 255 255"
	}

	"CTPlayerDeathsLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"CTPlayerDeathsLabel"
		"xpos"				"c-77"
		"ypos"				"c-125"
		"zpos"				"4"
		"wide"				"37"
		"tall"				"15"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"#Cstrike_SB_Deaths"
		"textAlignment"		"center"
		"font"				"ScoreboardColumns"
		"fgcolor_override"	"150 200 255 255"
	}

	"CTPlayerLatencyLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"CTPlayerLatencyLabel"
		"xpos"				"c-44"
		"ypos"				"c-125"
		"zpos"				"4"
		"wide"				"42"
		"tall"				"15"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"#Cstrike_SB_Latency"
		"textAlignment"		"center"
		"font"				"ScoreboardColumns"
		"fgcolor_override"	"150 200 255 255"
	}

	"CTPlayerList"
	{
		"ControlName"		"SectionedListPanel"
		"fieldName"			"CTPlayerList"
		"xpos"				"c-295"
		"ypos"				"c-124"
		"zpos"				"4"
		"wide"				"295"
		"tall"				"290"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"			"1"
		"enabled"			"1"
		"linespacing"		"13"	
		"sectionheader"		"0"
	}

	"TPlayerLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"TPlayerLabel"
		"xpos"				"c+11"
		"ypos"				"c-125"
		"zpos"				"4"
		"wide"				"60"
		"tall"				"15"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"#Cstrike_SB_PlayerName"
		"textAlignment"		"west"
		"font"				"ScoreboardColumns"
		"fgcolor_override"	"255 64 64 255"
	}

	"TPlayerScoreLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"TPlayerScoreLabel"
		"xpos"				"c+190"
		"ypos"				"c-125"
		"zpos"				"4"
		"wide"				"30"
		"tall"				"15"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"#Cstrike_SB_Score"
		"textAlignment"		"center"
		"font"				"ScoreboardColumns"
		"fgcolor_override"	"255 64 64 255"
	}

	"TPlayerDeathsLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"TPlayerDeathsLabel"
		"xpos"				"c+218"
		"ypos"				"c-125"
		"zpos"				"4"
		"wide"				"37"
		"tall"				"15"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"#Cstrike_SB_Deaths"
		"textAlignment"		"center"
		"font"				"ScoreboardColumns"
		"fgcolor_override"	"255 64 64 255"
	}

	"TPlayerLatencyLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"TPlayerLatencyLabel"
		"xpos"				"c+251"
		"ypos"				"c-125"
		"zpos"				"4"
		"wide"				"42"
		"tall"				"15"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"#Cstrike_SB_Latency"
		"textAlignment"		"center"
		"font"				"ScoreboardColumns"
		"fgcolor_override"	"255 64 64 255"
	}

	"TPlayerList"
	{
		"ControlName"		"SectionedListPanel"
		"fieldName"			"TPlayerList"
		"xpos"				"c+0"
		"ypos"				"c-124"
		"zpos"				"4"
		"wide"				"295"
		"tall"				"290"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"			"1"
		"enabled"			"1"
		"linespacing"		"13"
		"sectionheader"		"0"
	}

	"Spectators"
	{
		"ControlName"		"Label"
		"fieldName"			"Spectators"
		"labelText"			"%spectators%"
		"textAlignment"		"west"
		"xpos"				"c-288"
		"ypos"				"c+166"
		"zpos"				"90"
		"wide"				"485"
		"tall"				"15"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"fgcolor_override"	"216 220 223 255"
	}
}