"Resource/UI/TFTextWindow.res"
{
	"teammenu"
	{
		"ControlName"			"CTFTeamMenu"
		"fieldName"				"teammenu"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"f0"
		"tall"					"480"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"settitlebarvisible"	"0"
	}
	"Background"
	{
		"ControlName"	        "ScalableImagePanel"
		"fieldName"		        "Background"
		"xpos"		            "c-426"
		"ypos"		            "c-240"
		"zpos"					"0"
		"wide"		            "853"
		"tall"		            "480"
		"visible"				"1"
		"enabled"				"1"
		"image"					"team/ui_team"
		"scaleImage"			"1"
		"drawcolor"				"255 255 255 255"
	}
	"teambutton0"
	{
		"ControlName"	"TFTeamButton"
		"fieldName"		"teambutton0"
		"xpos"			"c-29"
		"ypos"			"101"
		"zpos"			"3"
		"wide"			"125"
		"tall"			"310"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"3"
		"labelText"		""
		"textAlignment"	"south-west"
		"dulltext"		"0"
		"brighttext"	"0"
		"paintborder"	"0"
		"command"		"jointeam 2"
		"team"				"2"		// team blue
		"associated_model"	"bluedoor"
		"hover"				"2.0"
		"fgcolor_override"		"Black"
	}

	"teambutton1"
	{
		"ControlName"	"TFTeamButton"
		"fieldName"		"teambutton1"
		"xpos"			"c159"
		"ypos"			"101"
		"zpos"			"3"
		"wide"			"125"
		"tall"			"310"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"4"
		"labelText"		""
		"textAlignment"	"south-west"
		"dulltext"		"0"
		"brighttext"	"0"
		"paintborder"	"0"
		"command"		"jointeam 1"
		"team"				"1"		// team red
		"associated_model"	"reddoor"	
		"hover"				"2.0"
		"fgcolor_override"		"Black"
	}

	"teambutton2"
	{
		"ControlName"	"TFTeamButton"
		"fieldName"		"teambutton2"
		"xpos"			"c-290"
		"ypos"			"101"
		"zpos"			"3"
		"wide"			"125"
		"tall"			"310"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"1"
		"labelText"		""
		"textAlignment"	"south-west"
		"dulltext"		"0"
		"brighttext"	"0"
		"paintborder"	"0"
		"command"		"jointeam 0"
		"associated_model"	"autodoor"
		"fgcolor_override"		"Black"
	}
	
	"teambutton3"
	{
		"ControlName"	"TFTeamButton"
		"fieldName"		"teambutton3"
		"xpos"			"c-140"
		"ypos"			"232"
		"zpos"			"3"
		"wide"			"82"
		"tall"			"57"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"2"
		"labelText"		""
		"textAlignment"	"south-west"
		"dulltext"		"0"
		"brighttext"	"0"
		"paintborder"	"0"
		"command"		"jointeam 3"
		"associated_model"	"spectate"	
		"fgcolor_override"		"Black"
	}
	"CancelButton"
	{
		"ControlName"	"Button"
		"fieldName"		"CancelButton"
		"xpos"			"r190"
		"xpos_hidef"			"r200"
		"ypos"			"r40"
		"ypos_lodef"			"r64"
		"ypos_hidef"			"r54"
		"zpos"			"6"
		"wide"			"150"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#CKF3_Cancel"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"command"		"cancelmenu"
		"font"			"MenuSmallFont"
	}
	
	"TeamMenuSelect"
	{
		"ControlName"	"Label"
		"fieldName"		"TeamMenuSelect"
		"xpos"			"30"
		"ypos"			"r40"
		"zpos"			"6"
		"wide"			"450"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#CKF3_SelectATeam"
		"textAlignment"	"west"
		"dulltext"		"0"
		"brighttext"	"0"
		"font"			"MenuMainTitle"
		"fgcolor_override"		"HudOffWhite"
	}
	
	"TeamMenuAuto"
	{
		"ControlName"	"Label"
		"fieldName"		"TeamMenuAuto"
		"xpos"			"c-280"
		"ypos"			"55"
		"zpos"			"1"
		"wide"			"102"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#CKF3_Random"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"wrap"			"0"
		"font"			"MenuSmallFont"
		"fgcolor_override"		"Black"
	}
	"TeamMenuSpectate"
	{
		"ControlName"	"Label"
		"fieldName"		"TeamMenuSpectate"
		"xpos"			"c-112"
		"ypos"			"255"
		"zpos"			"1"
		"wide"			"44"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#CKF3_Spectate"
		"textAlignment"	"north"
		"dulltext"		"0"
		"brighttext"	"0"
		"wrap"			"0"
		"font"			"MenuSmallestFont"
		"fgcolor_override"		"White"
	}
	"BlueCount"
	{
		"ControlName"	"Label"
		"fieldName"		"BlueCount"
		"xpos"			"c5"
		"ypos"			"53"
		"zpos"			"1"
		"wide"			"90"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"0"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"1"
		"font"			"TeamMenuBold"
		"fgcolor_override"		"Black"
	}		
	
	"RedCount"
	{
		"ControlName"	"Label"
		"fieldName"		"RedCount"
		"xpos"			"c193"
		"ypos"			"53"
		"zpos"			"1"
		"wide"			"90"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"0"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"1"
		"font"			"TeamMenuBold"
		"fgcolor_override"		"Black"
	}
	
	"bluedoor"
	{
		"ControlName"	"ModelPanel"
		"fieldName"		"bluedoor"
		"xpos"			"c-29"
		"ypos"			"101"
		"zpos"			"4"		
		"wide"			"125"
		"tall"			"310"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		
		"model"			"models/CKF_III/ui_selteam_doors.mdl"
		"skin"			"1"
		"angles" 		"0 0 0"
		"origin" 		"49 0 0"
	}
	
	"reddoor"
	{
		"ControlName"	"ModelPanel"
		"fieldName"		"reddoor"
		"xpos"			"c159"
		"ypos"			"101"
		"zpos"			"4"
		"wide"			"125"
		"tall"			"310"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		
		"model"			"models/CKF_III/ui_selteam_doors.mdl"
		"skin"			"2"
		"angles" 		"0 0 0"
		"origin" 		"49 0 0"
	}
	
	"autodoor"
	{
		"ControlName"	"ModelPanel"
		"fieldName"		"autodoor"
		"xpos"			"c-290"
		"ypos"			"101"
		"zpos"			"4"		
		"wide"			"125"
		"tall"			"310"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		
		"model"			"models/CKF_III/ui_selteam_doors.mdl"
		"skin"			"0"
		"angles" 		"0 0 0"
		"origin" 		"49 0 0"
	}
	
	"spectate"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"spectate"
		"xpos"			"c-140"
		"ypos"			"232"
		"zpos"			"4"		
		"wide"			"82"
		"tall"			"57"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"image"			"resource/tga/btn_selspe_1440_0"
		"scaleImage"	"1"
		"drawcolor"		"255 255 255 255"		
	}

	"bluedisable"
	{
		"ControlName"	        "ImagePanel"
		"fieldName"		        "bluedisable"
		"xpos"		            "c-10"
		"ypos"		            "c-10"
		"zpos"					"5"
		"wide"		            "32"
		"tall"		            "32"
		"visible"				"1"
		"enabled"				"1"
		"image"					"team/ico_disable"
		"scaleImage"			"1"
		"drawcolor"				"255 255 255 255"
	}
}
