"Resource/UI/TFTextWindow.res"
{
	"info"
	{
		"ControlName"			"CTFTextWindow"
		"fieldName"				"info"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"f0"
		"tall"					"480"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"settitlebarvisible"	"0"
	}
	"Background"
	{
		"ControlName"	        "ScalableImagePanel"
		"fieldName"		        "Background"
		"xpos"		            "c-426"
		"ypos"		            "c-240"
		"zpos"					"0"
		"wide"		            "853"
		"tall"		            "480"
		"visible"				"1"
		"enabled"				"1"
		"image"					"intro/ui_intro"
		"scaleImage"			"1"
		"drawcolor"			"255 255 255 255"
	}
	"Title"
	{
		"ControlName"		"Label"
		"fieldName"			"Title"
		"xpos"				"c-184"
		"ypos"				"c-143"
		"zpos"				"1"
		"wide"				"368"
		"tall"				"24"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			""
		"textAlignment"		"north-west"
		"font"				"ChalkboardTitle"
	}
	"Message"
	{
		"ControlName"		"TFRichText"
		"fieldName"			"Message"
		"xpos"				"c-184"
		"ypos"				"125"
		"zpos"				"1"
		"wide"				"415"
		"tall"				"240"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			""
		"textAlignment"		"north-west"
		"font"				"ChalkboardText"
	}
	"HTMLMessage"
	{
		"ControlName"		"HTML"
		"fieldName"		"HTMLMessage"
		"xpos"			"c-184"
		"ypos"			"75"
		"zpos"			"1"
		"wide"			"415"
		"tall"			"295"
		"autoResize"	"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"paintborder"	"0"
	}	
	"ok"
	{
		"ControlName"		"Button"
		"fieldName"		"ok"
		"xpos"			"r190"
		"ypos"			"r40"
		"zpos"			"6"
		"wide"			"150"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#CKF3_Continue"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"command"		"okay"
		"default"		"1"
		"font"			"MenuSmallFont"
	}
}
