"Resource/CreateMultiplayerGameBotPage.res"
{
	"BotPage"
	{
		"ControlName"		"CCreateMultiplayerGameBotPage"
		"fieldName"		"BotPage"
		"xpos"		"0"
		"ypos"		"28"
		"wide"		"332"
		"tall"		"367"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"BotAllowRogueCheck"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"BotAllowRogueCheck"
		"xpos"		"135"
		"ypos"		"178"
		"wide"		"190"
		"tall"		"22"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"4"
		"labelText"		"#CStrike_Bot_GoRogue"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"BotAllowPistolsCheck"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"BotAllowPistolsCheck"
		"xpos"		"135"
		"ypos"		"217"
		"wide"		"190"
		"tall"		"22"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"6"
		"labelText"		"#CStrike_Bot_UsePistols"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"BotAllowShotgunsCheck"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"BotAllowShotgunsCheck"
		"xpos"		"135"
		"ypos"		"237"
		"wide"		"190"
		"tall"		"22"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"7"
		"labelText"		"#CStrike_Bot_UseShotguns"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"BotAllowSubmachineGunsCheck"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"BotAllowSubmachineGunsCheck"
		"xpos"		"135"
		"ypos"		"257"
		"wide"		"200"
		"tall"		"22"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"8"
		"labelText"		"#CStrike_Bot_UseSub"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"BotAllowRiflesCheck"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"BotAllowRiflesCheck"
		"xpos"		"135"
		"ypos"		"277"
		"wide"		"190"
		"tall"		"22"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"10"
		"labelText"		"#CStrike_Bot_UseRifles"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"BotAllowMachineGunsCheck"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"BotAllowMachineGunsCheck"
		"xpos"		"135"
		"ypos"		"297"
		"wide"		"190"
		"tall"		"22"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"9"
		"labelText"		"#CStrike_Bot_UseMachineGuns"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"BotAllowSnipersCheck"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"BotAllowSnipersCheck"
		"xpos"		"135"
		"ypos"		"337"
		"wide"		"165"
		"tall"		"22"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"12"
		"labelText"		"#CStrike_Bot_UseSniper"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"BotAllowGrenadesCheck"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"BotAllowGrenadesCheck"
		"xpos"		"135"
		"ypos"		"317"
		"wide"		"165"
		"tall"		"22"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"11"
		"labelText"		"#CStrike_Bot_UseGrenades"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"BotJoinAfterPlayerCheck"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"BotJoinAfterPlayerCheck"
		"xpos"		"135"
		"ypos"		"138"
		"wide"		"190"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"3"
		"labelText"		"#CStrike_Bot_JoinAfterPlayer"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"BotDeferToHumanCheck"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"BotDeferToHumanCheck"
		"xpos"		"135"
		"ypos"		"158"
		"wide"		"195"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_Bot_Defer"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"BotJoinTeamCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"BotJoinTeamCombo"
		"xpos"		"142"
		"ypos"		"80"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"BotChatterCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"BotChatterCombo"
		"xpos"		"142"
		"ypos"		"110"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"BotPrefixEntry"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"BotPrefixEntry"
		"xpos"		"142"
		"ypos"		"20"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"BotPrefixLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"BotPrefixLabel"
		"xpos"		"24"
		"ypos"		"20"
		"wide"		"110"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#CStrike_Bot_NamePrefix"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	"BotProfileEntry"
	{
		"ControlName"		"TextEntry"
		"fieldName"		"BotProfileEntry"
		"xpos"		"142"
		"ypos"		"50"
		"wide"		"128"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"BotProfileLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"BotProfileLabel"
		"xpos"		"24"
		"ypos"		"50"
		"wide"		"110"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#CStrike_Bot_Profile"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	"BotJoinTeamLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"BotJoinTeamLabel"
		"xpos"		"24"
		"ypos"		"80"
		"wide"		"110"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#CStrike_Bot_JoinTeam"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	"Divider1"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider1"
		"xpos"		"18"
		"ypos"		"208"
		"wide"		"298"
		"tall"		"2"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"Label1"
	{
		"ControlName"		"Label"
		"fieldName"		"Label1"
		"xpos"		"24"
		"ypos"		"216"
		"wide"		"110"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#CStrike_Bot_AllowWeapon"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	"BotChatterLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"BotChatterLabel"
		"xpos"		"24"
		"ypos"		"110"
		"wide"		"110"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_Bot_Chatter"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
	}
}
 