"Resource/LoadingDialogDualProgress.res"
{
	"LoadingDialog"
	{
		"ControlName"		"Frame"
		"fieldName"		"LoadingDialog"
		"xpos"		"210"
		"ypos"		"162"
		"wide"		"380"
		"tall"		"180"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"1"
	}
	"progress"
	{
		"ControlName"		"ProgressBar"
		"fieldName"		"Progress"
		"xpos"		"20"
		"ypos"		"58"
		"wide"		"260"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"Progress2"
	{
		"ControlName"		"ProgressBar"
		"fieldName"		"Progress2"
		"xpos"		"20"
		"ypos"		"132"
		"wide"		"260"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"InfoLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"InfoLabel"
		"xpos"		"20"
		"ypos"		"34"
		"wide"		"340"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_VerifyingAndDownloading"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"CancelButton"
	{
		"ControlName"		"Button"
		"fieldName"		"CancelButton"
		"xpos"		"288"
		"ypos"		"132"
		"wide"		"72"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Cancel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"Cancel"
		"Default"		"1"
	}
	"SecondaryProgressLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"SecondaryProgressLabel"
		"xpos"		"20"
		"ypos"		"90"
		"wide"		"340"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		" "
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"TimeRemainingLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"TimeRemainingLabel"
		"xpos"		"20"
		"ypos"		"108"
		"wide"		"260"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
}