"Resource\OptionsSubMouse.res"
{
	"ReverseMouse"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"ReverseMouse"
		"xpos"		"36"
		"ypos"		"32"
		"wide"		"140"
		"tall"		"28"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"labelText"		"#GameUI_ReverseMouse"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"Reverse Mouse label"
	{
		"ControlName"		"Label"
		"fieldName"		"Reverse Mouse label"
		"xpos"		"184"
		"ypos"		"35"
		"wide"		"300"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_ReverseMouseLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"MouseLook"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"MouseLook"
		"xpos"		"36"
		"ypos"		"54"
		"wide"		"140"
		"tall"		"28"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"labelText"		"#GameUI_MouseLook"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"MouseLookLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"Label1"
		"xpos"		"184"
		"ypos"		"57"
		"wide"		"300"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_MouseLookLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"MouseFilter"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"MouseFilter"
		"xpos"		"36"
		"ypos"		"76"
		"wide"		"140"
		"tall"		"28"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"3"
		"labelText"		"#GameUI_MouseFilter"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"MouseFilterLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"Mouse filter"
		"xpos"		"184"
		"ypos"		"79"
		"wide"		"300"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_MouseFilterLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"Joystick"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"Joystick"
		"xpos"		"36"
		"ypos"		"98"
		"wide"		"140"
		"tall"		"28"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"4"
		"labelText"		"#GameUI_Joystick"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"JoystickLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"Joystick label"
		"xpos"		"184"
		"ypos"		"101"
		"wide"		"300"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_JoystickLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"JoystickLook"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"JoystickLook"
		"xpos"		"36"
		"ypos"		"120"
		"wide"		"140"
		"tall"		"28"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"5"
		"labelText"		"#GameUI_JoystickLook"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"Label2"
	{
		"ControlName"		"Label"
		"fieldName"		"Label2"
		"xpos"		"184"
		"ypos"		"123"
		"wide"		"300"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_JoystickLookLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"Auto-Aim"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"Auto-Aim"
		"xpos"		"36"
		"ypos"		"142"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"labelText"		"#GameUI_AutoAim"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"AutoaimLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"AutoaimLabel"
		"xpos"		"184"
		"ypos"		"145"
		"wide"		"300"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_AutoaimLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"RawInput"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"RawInput"
		"xpos"		"36"
		"ypos"		"164"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"labelText"		"#GameUI_RawInput"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"RawInputLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"RawInputLabel"
		"xpos"		"184"
		"ypos"		"167"
		"wide"		"300"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_RawInputLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"Label3"
	{
		"ControlName"		"Label"
		"fieldName"		"Label3"
		"xpos"		"40"
		"ypos"		"202"
		"wide"		"164"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_MouseSensitivity"
		"textAlignment"		"west"
		"associate"		"Slider"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	"Slider"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"Slider"
		"xpos"		"40"
		"ypos"		"224"
		"wide"		"272"
		"tall"		"40"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"6"
	}  
	"SensitivityLabel"     
	{
		"ControlName"		"TextEntry"
		"fieldName"		"SensitivityLabel"
		"xpos"		"320"
		"ypos"		"224"
		"wide"		"48"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"NumericInputOnly"	"1"
	}
}
