"Resource\OptionsSubVideo.res"
{
	"Brightness"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"Brightness"
		"xpos"		"40"
		"ypos"		"189"
		"wide"		"160"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"6"
		"leftText"		"#GameUI_DARK"
		"rightText"		"#GameUI_LIGHT"
	}
	"Gamma"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"Gamma"
		"xpos"		"256"
		"ypos"		"189"
		"wide"		"160"
		"tall"		"50"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"7"
		"leftText"		"#GameUI_LOW"
		"rightText"		"#GameUI_HIGH"
	}

	"Resolution"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"Resolution"
		"xpos"		"40"
		"ypos"		"56"
		"wide"		"160"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"AspectRatio"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"AspectRatio"
		"xpos"		"40"
		"ypos"		"122"
		"wide"		"160"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"3"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"AdvancedButton"
	{
		"ControlName"		"Button"
		"fieldName"		"AdvancedButton"
		"xpos"		"256"
		"ypos"		"56"
		"wide"		"160"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"5"
		"labelText"		"#GameUI_AdvancedEllipsis"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"BenchmarkButton"
	{
		"ControlName"		"Button"
		"fieldName"		"BenchmarkButton"
		"xpos"		"39"
		"ypos"		"230"
		"wide"		"130"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_LaunchBenchmarkVideoPanel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"DisplayModeCombo"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"DisplayModeCombo"
		"xpos"		"254"
		"ypos"		"50"
		"wide"		"182"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"		"2"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"Windowed"
	{
		"ControlName"		"CheckButton"
		"fieldName"		"Windowed"
		"xpos"		"249"
		"ypos"		"87"
 		"wide"		"165"
		"tall"		"28"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"5"
		"labelText"		"#GameUI_Windowed"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"Default"		"0"
	}
	"brightness label"
	{
		"ControlName"		"Label"
		"fieldName"		"brightness label"
		"xpos"		"40"
		"ypos"		"167"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Brightness"
		"textAlignment"		"west"
		"associate"		"Brightness"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	"Gamma label"
	{
		"ControlName"		"Label"
		"fieldName"		"Gamma label"
		"xpos"		"256"
		"ypos"		"167"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Gamma"
		"textAlignment"		"west"
		"associate"		"Gamma"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	"Renderer"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"Renderer"
		"xpos"		"40"
		"ypos"		"52"
		"wide"		"160"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"Label1"
	{
		"ControlName"		"Label"
		"fieldName"		"Label1"
		"xpos"		"40"
		"ypos"		"30"
		"wide"		"160"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Resolution"
		"textAlignment"		"west"
		"associate"		"Resolution"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Label2"
	{
		"ControlName"		"Label"
		"fieldName"		"Label2"
		"xpos"		"40"
		"ypos"		"28"
		"wide"		"160"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Renderer"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Label4"
	{
		"ControlName"		"Label"
		"fieldName"		"Label4"
		"xpos"		"254"
		"ypos"		"24"
		"wide"		"160"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"		"0"
		"labelText"		"#GameUI_DisplayMode"
		"textAlignment"		"west"
		"associate"		"DisplayModeCombo"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Label5"
	{
		"ControlName"		"Label"
		"fieldName"		"Label5"
		"xpos"		"40"
		"ypos"		"246"
		"wide"		"450"
		"tall"		"47"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_VideoRestart"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"wrap"			"1"
	}
	"AspectRatioLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"AspectRatioLabel"
		"xpos"		"40"
		"ypos"		"96"
		"wide"		"160"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_AspectRatio"
		"textAlignment"		"west"
		"associate"		"AspectRatio"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
}
