"Resource/OptionsSubMultiplayer.res"
{
	"Cancel"
	{
		"ControlName"		"Button"
		"fieldName"		"Cancel"
		"xpos"		"378"
		"ypos"		"322"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"3"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#GameUI_Cancel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"Close"
		"Default"		"0"
	}
	"ok"
	{
		"ControlName"		"Button"
		"fieldName"		"OK"
		"xpos"		"308"
		"ypos"		"322"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"3"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#GameUI_OK"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"Ok"
		"Default"		"0"
	}
	"Apply"
	{
		"ControlName"		"Button"
		"fieldName"		"Apply"
		"xpos"		"448"
		"ypos"		"322"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"3"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#GameUI_Apply"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"Apply"
		"Default"		"0"
	}
	"Advanced"
	{
		"ControlName"		"Button"
		"fieldName"		"Advanced"
		"xpos"		"40"
		"ypos"		"260"
		"wide"		"120"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"9"
		"paintbackground"		"1"
		"labelText"		"#GameUI_AdvancedEllipsis"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Command"		"Advanced"
		"Default"		"1"
	}
	"NameLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"NameLabel"
		"xpos"		"40"
		"ypos"		"28"
		"wide"		"150"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#GameUI_PlayerName"
		"textAlignment"		"west"
		"associate"		"NameEntry"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"NameEntry"
	{
		"ControlName"		"CCvarTextEntry"
		"fieldName"		"NameEntry"
		"xpos"		"40"
		"ypos"		"52"
		"wide"		"196"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"63"
		"NumericInputOnly"		"0"
		"unicode"		"1"
	}
	"Primary Color Slider"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"Primary Color Slider"
		"xpos"		"20"
		"ypos"		"188"
		"wide"		"140"
		"tall"		"39"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"3"
		"paintbackground"		"1"
		"leftText"		" "
		"rightText"		" "
	}
	"Secondary Color Slider"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"Secondary Color Slider"
		"xpos"		"20"
		"ypos"		"225"
		"wide"		"140"
		"tall"		"42"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"4"
		"paintbackground"		"1"
		"leftText"		" "
		"rightText"		" "
	}
	"High Quality Models"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"High Quality Models"
		"xpos"		"190"
		"ypos"		"259"
		"wide"		"174"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"5"
		"paintbackground"		"1"
		"labelText"		"#GameUI_HighModels"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"Player model"
	{
		"ControlName"		"CLabeledCommandComboBox"
		"fieldName"		"Player model"
		"xpos"		"40"
		"ypos"		"122"
		"wide"		"140"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"2"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"SpraypaintList"
	{
		"ControlName"		"CLabeledCommandComboBox"
		"fieldName"		"SpraypaintList"
		"xpos"		"112"
		"ypos"		"120"
		"wide"		"124"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"SpraypaintColor"
	{
		"ControlName"		"CLabeledCommandComboBox"
		"fieldName"		"SpraypaintColor"
		"xpos"		"112"
		"ypos"		"160"
		"wide"		"124"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"3"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"ModelImage"
	{
		"ControlName"		"Panel"
		"fieldName"		"ModelImage"
		"xpos"		"176"
		"ypos"		"36"
		"wide"		"164"
		"tall"		"200"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
	}
	"LogoImage"
	{
		"ControlName"		"Panel"
		"fieldName"		"LogoImage"
		"xpos"		"40"
		"ypos"		"120"
		"wide"		"64"
		"tall"		"64"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
	}
	"CrosshairColorComboBox"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"CrosshairColorComboBox"
		"xpos"		"354"
		"ypos"		"155"
		"wide"		"108"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"8"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"CrosshairSizeComboBox"
	{
		"ControlName"		"CLabeledCommandComboBox"
		"fieldName"		"CrosshairSizeComboBox"
		"xpos"		"354"
		"ypos"		"120"
		"wide"		"108"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"6"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"CrosshairTypeComboBox"
	{
		"ControlName"		"CLabeledCommandComboBox"
		"fieldName"		"CrosshairTypeComboBox"
		"xpos"		"354"
		"ypos"		"190"
		"wide"		"108"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"CrosshairTranslucencyCheckbox"
	{
		"ControlName"		"CCvarToggleCheckButton"
		"fieldName"		"CrosshairTranslucencyCheckbox"
		"xpos"		"348"
		"ypos"		"223"
		"wide"		"101"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"0"
		"labelText"		"#GameUI_Translucent"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"Default"		"0"
	}
	"CrosshairImage"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"CrosshairImage"
		"xpos"		"281"
		"ypos"		"120"
		"wide"		"64"
		"tall"		"64"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"image"		"gfx/vgui/crosshair"
		"border"		"InsetBorder"
		"scaleImage"		"0"
	}
	"URLLabel1"
	{
		"ControlName"		"URLLabel"
		"fieldName"		"URLLabel1"
		"xpos"		"245"
		"ypos"		"44"
		"wide"		"250"
		"tall"		"40"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"1"
		"paintbackground"		"1"
		"labelText"		"#GameUI_SetSteamCommunityName"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"1"
		"URLText"		"steam://settings/friends"
	}
	"CrosshairLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"CrosshairLabel"
		"xpos"		"281"
		"ypos"		"94"
		"wide"		"181"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#GameUI_CrosshairDescription"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"SysMenu"
	{
		"ControlName"		"Menu"
		"fieldName"		"SysMenu"
		"xpos"		"0"
		"ypos"		"0"
		"zpos"		"1"
		"wide"		"64"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
	}
	"topHorizLeft"
	{
		"ControlName"		"Label"
		"fieldName"		"topHorizLeft"
		"xpos"		"186"
		"ypos"		"120"
		"wide"		"21"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"392"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"topVertLeft"
	{
		"ControlName"		"Label"
		"fieldName"		"topVertLeft"
		"xpos"		"374"
		"ypos"		"58"
		"wide"		"21"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"133"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"bottomHorizRight"
	{
		"ControlName"		"Label"
		"fieldName"		"bottomHorizRight"
		"xpos"		"508"
		"ypos"		"176"
		"wide"		"21"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"133"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"bottomVertRight"
	{
		"ControlName"		"Label"
		"fieldName"		"bottomVertRight"
		"xpos"		"496"
		"ypos"		"260"
		"wide"		"6"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"133"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Colors"
	{
		"ControlName"		"Label"
		"fieldName"		"Colors"
		"xpos"		"20"
		"ypos"		"164"
		"wide"		"88"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#GameUI_ColorSliders"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Label1"
	{
		"ControlName"		"Label"
		"fieldName"		"Label1"
		"xpos"		"40"
		"ypos"		"98"
		"wide"		"152"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#GameUI_PlayerModel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Label2"
	{
		"ControlName"		"Label"
		"fieldName"		"Label2"
		"xpos"		"40"
		"ypos"		"94"
		"wide"		"120"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#GameUI_SpraypaintImage"
		"textAlignment"		"west"
		"associate"		"SpraypaintList"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Label3"
	{
		"ControlName"		"Label"
		"fieldName"		"Label3"
		"xpos"		"40"
		"ypos"		"187"
		"wide"		"230"
		"tall"		"64"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintbackground"		"1"
		"labelText"		"#GameUI_SpraypaintServerNote"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"wrap"		"1"
	}
}
 
