"classes/defuser.res"
{
	"pricelabel"
	{
		"ControlName"		"Label"
		"fieldName"		"infolabel"
			"xpos"		"0"
		"ypos"		"138"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_PriceLabel"
		"textAlignment"		"north-west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}

	"descriptionlabel"
	{
		"ControlName"		"Label"
		"fieldName"		"descriptionlabel"
		"xpos"		"0"
		"ypos"		"156"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_DescriptionLabel"
		"textAlignment"		"north-west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}

	"price"
	{
		"ControlName"		"Label"
		"fieldName"		"infolabel"
		"xpos"		"140"
		"ypos"		"138"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_DefuserPrice"
		"textAlignment"		"north-west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}

	"description"
	{
		"ControlName"		"Label"
		"fieldName"		"description"
		"xpos"		"140"
		"ypos"		"156"
		"wide"		"150"
		"tall"		"64"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_DefuserDescription"
		"textAlignment"		"north-west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}
	"imageBG"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"imageBG"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"300"
		"tall"		"128"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"center"
		"fillColor"		"WindowBG"
	}
	"classimage"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"classimage"
		"xpos"		"0"
		"ypos"		"4"
		"wide"		"256"
		"tall"		"128"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"west"
		"image"			"gfx/vgui/defuser"
		"scaleImage"	"1"
	}
	"imageBorder"
	{
		"ControlName"		"Divider"
		"fieldName"		"imageBorder"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"300"
		"tall"		"128"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"zpos"		"2"
	}
}