"classes/p228.res"
{
	"pricelabel"
	{
		"ControlName"		"Label"
		"fieldName"		"pricelabel"
		"xpos"		"0"
		"ypos"		"126"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#CStrike_PriceLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}

	"originlabel"
	{
		"ControlName"		"Label"
		"fieldName"		"originlabel"
		"xpos"		"0"
		"ypos"		"138"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#CStrike_OriginLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}
	"calibrelabel"
	{
		"ControlName"		"Label"
		"fieldName"		"calibrelabel"
		"xpos"		"0"
		"ypos"		"150"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#CStrike_CalibreLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}
	"clipcapacitylabel"
	{
		"ControlName"		"Label"
		"fieldName"		"calipcapacitylabel"
		"xpos"		"0"
		"ypos"		"162"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#CStrike_ClipCapacityLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}
	"rateoffirelabel"
	{
		"ControlName"		"Label"
		"fieldName"		"rateoffirelabel"
		"xpos"		"0"
		"ypos"		"174"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#CStrike_RateOfFireLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}
	"weightloadedlabel"
	{
		"ControlName"		"Label"
		"fieldName"		"weightloadedlabel"
		"xpos"		"0"
		"ypos"		"186"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#CStrike_WeightLoadedLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}
	"projectileweightlabel"
	{
		"ControlName"		"Label"
		"fieldName"		"projectileweightlabel"
		"xpos"		"0"
		"ypos"		"198"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#CStrike_ProjectileWeightLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}
	"muzzlevelocitylabel"
	{
		"ControlName"		"Label"
		"fieldName"		"muzzlevelocitylabel"
		"xpos"		"0"
		"ypos"		"210"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#CStrike_MuzzleVelocityLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}
	"muzzleenergylabel"
	{
		"ControlName"		"Label"
		"fieldName"		"muzzleenergylabel"
		"xpos"		"0"
		"ypos"		"222"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#CStrike_MuzzleEnergyLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}

	"price"
	{
		"ControlName"		"Label"
		"fieldName"		"price"
		"xpos"		"140"
		"ypos"		"126"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_P228Price"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}
	"origin"
	{
		"ControlName"		"Label"
		"fieldName"		"origin"
		"xpos"		"140"
		"ypos"		"138"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_P228Origin"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}
	"calibre"
	{
		"ControlName"		"Label"
		"fieldName"		"calibre"
		"xpos"		"140"
		"ypos"		"150"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_P228Calibre"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}
	"clipcapacity"
	{
		"ControlName"		"Label"
		"fieldName"		"calipcapacity"
		"xpos"		"140"
		"ypos"		"162"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_P228ClipCapacity"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}
	"rateoffire"
	{
		"ControlName"		"Label"
		"fieldName"		"rateoffire"
		"xpos"		"140"
		"ypos"		"174"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_P228RateOfFire"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}
	"weightempty"
	{
		"ControlName"		"Label"
		"fieldName"		"weightempty"
		"xpos"		"140"
		"ypos"		"186"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_P228WeightLoaded"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}
	"projectileweight"
	{
		"ControlName"		"Label"
		"fieldName"		"projectileweight"
		"xpos"		"140"
		"ypos"		"198"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_P228ProjectileWeight"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}
	"muzzlevelocity"
	{
		"ControlName"		"Label"
		"fieldName"		"muzzlevelocity"
		"xpos"		"140"
		"ypos"		"210"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_P228MuzzleVelocity"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}
	"muzzleenergy"
	{
		"ControlName"		"Label"
		"fieldName"		"muzzleenergy"
		"xpos"		"140"
		"ypos"		"222"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_P228MuzzleEnergy"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultVerySmall"
	}
	"imageBG"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"imageBG"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"300"
		"tall"		"128"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"center"
		"fillColor"		"WindowBG"
	}
	"classimage"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"classimage"
		"xpos"		"0"
		"ypos"		"8"
		"wide"		"256"
		"tall"		"128"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"west"
		"image"			"gfx/vgui/p228"
		"scaleImage"	"1"
	}
	"imageBorder"
	{
		"ControlName"		"Divider"
		"fieldName"		"imageBorder"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"300"
		"tall"		"128"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"zpos"		"2"
	}
}