"classes/scout.res"
{

	"pricelabel"
	{
		"ControlName"		"Label"
		"fieldName"		"pricelabel"
		"xpos"		"0"
		"ypos"		"86"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#CStrike_PriceLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}

	"originlabel"
	{
		"ControlName"		"Label"
		"fieldName"		"originlabel"
		"xpos"		"0"
		"ypos"		"102"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#CStrike_OriginLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"calibrelabel"
	{
		"ControlName"		"Label"
		"fieldName"		"calibrelabel"
		"xpos"		"0"
		"ypos"		"118"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#CStrike_CalibreLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"clipcapacitylabel"
	{
		"ControlName"		"Label"
		"fieldName"		"calipcapacitylabel"
		"xpos"		"0"
		"ypos"		"134"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#CStrike_ClipCapacityLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"rateoffirelabel"
	{
		"ControlName"		"Label"
		"fieldName"		"rateoffirelabel"
		"xpos"		"0"
		"ypos"		"150"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#CStrike_RateOfFireLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"weightlabel"
	{
		"ControlName"		"Label"
		"fieldName"		"weightlabel"
		"xpos"		"0"
		"ypos"		"166"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#CStrike_WeightEmptyLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"projectileweightlabel"
	{
		"ControlName"		"Label"
		"fieldName"		"projectileweightlabel"
		"xpos"		"0"
		"ypos"		"182"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#CStrike_ProjectileWeightLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"muzzlevelocitylabel"
	{
		"ControlName"		"Label"
		"fieldName"		"muzzlevelocitylabel"
		"xpos"		"0"
		"ypos"		"198"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#CStrike_MuzzleVelocityLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"muzzleenergylabel"
	{
		"ControlName"		"Label"
		"fieldName"		"muzzleenergylabel"
		"xpos"		"0"
		"ypos"		"214"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#CStrike_MuzzleEnergyLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}

	"price"
	{
		"ControlName"		"Label"
		"fieldName"		"price"
		"xpos"		"140"
		"ypos"		"86"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_ScoutPrice"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"origin"
	{
		"ControlName"		"Label"
		"fieldName"		"origin"
		"xpos"		"140"
		"ypos"		"102"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_ScoutOrigin"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"calibre"
	{
		"ControlName"		"Label"
		"fieldName"		"calibre"
		"xpos"		"140"
		"ypos"		"118"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_ScoutCalibre"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"clipcapacity"
	{
		"ControlName"		"Label"
		"fieldName"		"calipcapacity"
		"xpos"		"140"
		"ypos"		"134"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_ScoutClipCapacity"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"rateoffire"
	{
		"ControlName"		"Label"
		"fieldName"		"rateoffire"
		"xpos"		"140"
		"ypos"		"150"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_ScoutRateOfFire"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"weight"
	{
		"ControlName"		"Label"
		"fieldName"		"weight"
		"xpos"		"140"
		"ypos"		"166"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_ScoutWeightEmpty"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"projectileweight"
	{
		"ControlName"		"Label"
		"fieldName"		"projectileweight"
		"xpos"		"140"
		"ypos"		"182"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_ScoutProjectileWeight"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"muzzlevelocity"
	{
		"ControlName"		"Label"
		"fieldName"		"muzzlevelocity"
		"xpos"		"140"
		"ypos"		"198"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_ScoutMuzzleVelocity"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"muzzleenergy"
	{
		"ControlName"		"Label"
		"fieldName"		"muzzleenergy"
		"xpos"		"140"
		"ypos"		"214"
		"wide"		"150"
		"tall"		"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_ScoutMuzzleEnergy"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"imageBG"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"imageBG"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"300"
		"tall"		"80"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"center"
		"fillColor"		"WindowBG"
	}
	"classimage"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"classimage"
		"xpos"		"0"
		"ypos"		"8"
		"wide"		"256"
		"tall"		"64"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"west"
		"image"			"gfx/vgui/scout"
		"scaleImage"	"1"
	}
	"imageBorder"
	{
		"ControlName"		"Divider"
		"fieldName"		"imageBorder"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"300"
		"tall"		"80"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"zpos"		"2"
	}
}