"classes/terror.res"
{
	"imageBG"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"imageBG"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"256"
		"tall"		"196"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"center"
		"fillColor"		"WindowBG"
		"zpos"		"0"
	}
	"classimage"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"classimage"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"256"
		"tall"		"196"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"west"
		"image"			"gfx/vgui/terror"
		"scaleImage"	"1"
		"zpos"		"1"
	}
	"imageBorder"
	{
		"ControlName"		"Divider"
		"fieldName"		"imageBorder"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"256"
		"tall"		"196"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"zpos"		"2"
	}
	"className"
	{
		"ControlName"		"Label"
		"fieldName"		"infolabel"
		"xpos"		"0"
		"ypos"		"204"
		"wide"		"300"
		"tall"		"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_Terror_Name"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
	}
	"infolabel"
	{
		"ControlName"		"Label"
		"fieldName"		"infolabel"
		"xpos"		"0"
		"ypos"		"228"
		"wide"		"300"
		"tall"		"80"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_Terror_Label"
		"textAlignment"		"north-west"
		"dulltext"		"1"
		"brighttext"		"0"
		"font"		"DefaultSmall"
	}
}